### ISSUE TITLE
base-loading 样式错位

### ISSUE THREAD

**Issue by aShu-guo** [antdv-pro/antdv-pro#79]
![image](https://github.com/antdv-pro/antdv-pro/assets/65716236/d4627611-1dd0-42d1-98c9-5c603d30ab8e)

原因：

```vue
 <div
          style={modal ? { background } : {}}
          class={{ 'loading-container': true, 'is-fullscreen': full }}
        >
          <div class="loading-wrapper">
            {renderBasicLoading() }
          </div>
          <div class="text" style={{ color: textColor }}>
              {text}
          </div>
</div>
```

```css
.loading-wrapper {
    position: absolute;
    top: 50%;
    width: 100%;
    margin-top: -21px;
    text-align: center;

    .text {
      width: 100%;
      margin: 8px 0;
    }

    .loading-icon {
      animation: rotating 1.5s linear infinite;
    }
  }
```

css层级不正确，导致样式未添加成功
